### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by vberger** [vberger/wayland-client-rs#10]
There is still a lot missing

**Comment by TLTimothy** [comment]
Hi, I'm looking for documentation jobs. Do you need help?

**Comment by vberger** [comment]
Right now, I'm still probably going to do some big change in the new structure of the lib for 0.3, but once this is done (hopefully it's a matter of 1 or 2 days), yeah sure !

A big part of the API is generated from the .xml protocol files, so their documentation is already included. However the generic API will need to be fully-documented as well.

**Comment by TLTimothy** [comment]
K, looking forward to it.

**Comment by vberger** [comment]
Most of the heavy work is done now. :smile:
