### ISSUE TITLE
Add server lib support

### ISSUE THREAD

**Issue by vberger** [vberger/wayland-client-rs#12]
Should be able to reuse a lot of the client code generation.

- [x] : FFI integration in `wayland-sys`
- [ ] : scanner integration
- [ ] : `wayland-server` lib

**Comment by fangyuanziti** [comment]
Hi, do you have a plan (in detail) to implement this? Looking forward for it.

**Comment by vberger** [comment]
It's mostly a matter of doing exactly the same thing as have been done for the client part, modulo some refactoring and splitting crates.

Mostly, my aim would be:
- a `wayland-sys` crate, containing what is currently in `src/abi/`, with several cargo flags (`dlopen`, `client`, `server`, `egl`, ...)
- a `wayland-scanner` crate containing the scanner

The end users would not need to directly use those crates, but they would be the building blocks of protocol-specific crates.

Then, the `wayland-client` crate would remain the implementation of the client core protocol. A `wayland-server` would be its server-side alter-ego. And other protocols would have their own crates (`xdg_shell` for example), with cargo flags `client`, `server` and `dlopen` as appropriate.

But right now I'm in discussions on the wayland-dev mailing list with the core-devs and other binding-writers to figure out a few details about type-safety in the xml protocol specifications, hence the lack of recent activity. But I'm getting back to it, now that I have a clearer idea of future design. :smile:

**Comment by fangyuanziti** [comment]
Thank you for your patient reply.
Actually, I am trying to build my wayland rust binding (given up after found this project :smile: ). My goal is to implement a wayland compositor in Rust which providing websocket/HTTP api (something like Gtk Broadway backend). 
So, I will provide some help for this job if you’d like.

**Comment by vberger** [comment]
Good to know! Any help would be much welcome!

I'm currently reorganising the things. To be honest, my P1 is finalizing the v0.3.0 of wayland-client, using the new architecture. Once this is done (hopefully during this weekend), I'll start tackling the server side.

**Comment by vberger** [comment]
This is now P1 for the next release, work in progress on #44

**Comment by vberger** [comment]
Probably won't be out for 0.6 actually, there are some important changes that need to be published for client, and server really needs more thinking about the API, which will certainly be very different of the client one...
