### ISSUE TITLE
Future-proof the `Event` enum

### ISSUE THREAD

**Issue by vberger** [vberger/wayland-client-rs#29]
Ideally, adding a new protocol to the library should not be a breaking change at all. This would allow to easily use cargo features to enable / disable protocols.

My only idea to do that for now would be to define the `Event` enum like this:

```rust
pub enum Event {
    Wayland(::wayland::WaylandProtocolEvent),
    #[cfg(feature = "protocol1"]
    Protocol1(::protocol1::Protocol1Event),
    #[cfg(feature = "protocol2"]
    Protocol2(::protocol2::Protocol2Event),
    /* etc ... */
    #[doc(hidden)]
    __HiddenVariantNotToBeMatched,
}
```

The idea of this last hidden variant would be to force matching on this enum to have a `_ => { ... }` branch, to handle unknown event (normally by ignoring them). This branch would actually never be taken, as it is not possible to receive messages from a proxy defined by a secondary protocol as long as you haven't created it !

This would pragmatically future-proof the enum, making adding new variant automatically be handled in the good way (caught by the `_` pattern).

Are there better options ?

**Comment by vohebup** [comment]
If for adding protocol extensions do not have to fork the project, you can put the enum in an external `config.rs` file and in the bowels themselves of bindings to use the macro `include!`

**Comment by vberger** [comment]
Adding other protocols without integrating them directly in the `wayland-client` crate is a difficult problem, because of the event machinery, which is quite centralized.

However, I tried to design `wayland-client` so that adding new protocols is really straightforward, using the scanner. And I plan to integrate as many other protocols as possible, if possible under cargo features.
