### ISSUE TITLE
Publish a new version of wayland-client to crates.io

### ISSUE THREAD

**Issue by fabricedesre** [vberger/wayland-client-rs#48]
https://crates.io/crates/wayland-client is 0.5.10 which still depends on dlib 0.2.0
That makes it conflict with wayland-kbd which depends on dlib 0.3.0

**Comment by mbrubeck** [comment]
Fixing this will require a PR to the `v0.5.x` branch:

https://github.com/vberger/wayland-client-rs/blob/v0.5.x/wayland-client/Cargo.toml

**Comment by vberger** [comment]
I've fixed the dependencies in f25c33b661a9519838d0412df546b35404592634 and am publishing version `0.5.11` of `wayland-scanner`, `wayland-sys` and `wayland-client` (might take some time, I've a very slow internet connexion where I am :wink: ).

**Comment by vberger** [comment]
Done. :smile:

**Comment by fabricedesre** [comment]
Thanks!
