### ISSUE TITLE
Library libwayland-server.so could not be loaded

### ISSUE THREAD

**Issue by Timidger** [vberger/wayland-client-rs#57]
Hey, I was trying to use your library, specfically with the `dlopen` feature in order to use the functions defined in the `WaylandServer` struct, and after running my program I get a panic saying `libwayland-server.so` could not be found. However, `ldd` reports that the binary can find `libwayland-server.so` on my system, is there something I'm missing or is this feature not complete yet?

**Comment by Timidger** [comment]
Whoops, nevermind. Didn't read the documentation enough and found `ffi_dispatch!` which does what I want without `dlopen`. As a curious aside however, why was `dlopen` not working correctly, even though `ldd` was reporting that the library was in the right spot?

**Comment by vberger** [comment]
wayland-sys is built using https://github.com/vberger/dlib/ for the `dlopen` trick, see its readme, I think it should be clear (and if it is not, please open an issue about it there :wink: ).
