### ISSUE TITLE
[discussion] Lib design

### ISSUE THREAD

**Issue by vberger** [vberger/wayland-client-rs#59]
This has bugged me for some time now, so I'm asking for outside input.

The wayland C library has a very callback oriented design: when you create an object, you register several functions to handle its events, in the form

```c
void event_vallback(wl_proxy* object, void* user_data, ...) { /* .. */ }
```

This works in C because the language is ok with having pointers all other the place and shared mutable globals and all, which is obviously not an option with Rust.

My first attempt at this lib (`v0.1` and `v0.2`) was to just copy this design, and let the user provide closures for the callbacks. For safety reasons, closures had to be `Send+Sync+'static`, because wayland is supposed to be threadsafe, which led to a nightmare to handle program state, with lots of `Arc<Mutex<_>>` even on single-threaded programs, which is obviously bad.

Second attempt (`v0.3` to `v0.6`) wraps the events into an `EventIterator`, letting the user of the lib handle the dispatching themselves, and thus side stepping the issue with previous attempts.

However this approach has its share of issues:

- deeply nested enums to represent the events
- no easy way to use a protocol extension but to patch `wayland-client`, as the events must be integrated in the `Event` enum
- This design does not match at all for `wayland-server` : server-side, the lifetime of all protocol objects is controlled by the client, and thus is not really representable server-side out of a callback-based design.

All this makes me not completely happy with the current design. Especially given I'd like as much as possible to share a common design between `wayland-client` and `wayland-server`, and make it easy to use 3rd party protocol extensions. As such, I'm thinking about going back to callback-based design, but different from the first one.

Rather go by traits to define handlers. Probably one trait for each wayland object. The use would then give to the lib one or several objects implementing the appropriate handler traits, and let it do the dispatching of events. The interest of this approach is that as the lib has ownership of the object, all handler methods can take `&mut self` without need for more synchronization mechanisms, the rest is fully guaranteed by the wayland C library.

The two central methods of the `EventLoop` interface would probably be something like that

```rust
impl<S> EventLoop<S> {
    /// Handle all wayland pending events and dispatch them to appropriate handlers
    fn dispatch(&smut self) { /* ... */ }

    /// Get access to the internal state, to handle non-wayland events for example
    fn get_state(&mut self) -> &mut S { /* ... */ }
}
```

Here, the Rust borrowing rules can guarantee that no callback can be called while a reference to the state is held elsewhere, as callbacks are called during the execution of the `dispatch(...)` method. Note that the wayland C library also provide the necessary mechanisms to have more than one event-loop, and assign each wayland object to the appropriate one (for example to handle keyboard and drawing events in different threads).

Now, I have still some unresolved questions about this:

- Is this a good idea at all?
- How to handle the registration of which handler traits are implemented and should be dispatched for?
- Could it be possible to attache several state objects to the same event loop, each implementing a different subset of the handler traits?
- Certainly several other questions that have not yet popped up...

**Comment by vberger** [comment]
Indeed, there are a few exceptions, however in most cases, you cannot just assume the program has control over the lifetime of the object (as opposed to a client, for which it's almost always true in practice, except for wl_callback objects), which is quite the opposite of Rust natural scheme.

**Comment by Timidger** [comment]
I'm in the middle of writing a Wayland WM/compositor with Rust, and the project has finally gotten to the point where it needs to start speaking the various Wayland protocols. 

I totally agree that the current design, especially on the server side (which I can honestly not make heads or tails of, how do I bind a function to respond to an event from a client?), is not the best. The client library is not as difficult to work with, but it would also stand to benefit from the much more flexible trait-based approach. 

Since this is so vital to my project, if there is any help you need that I can provide during the rewrite I'd be happy to contribute what I can.

**Comment by vberger** [comment]
@Timidger : Just, to be clear : the `wayland-server` lib is nowhere near usable state. I kind of dropped it in the middle of writing it when I realized how much I would not be able to do what I initially planned.

However, I think I've a good idea of how I'll organise this trait-based approach, and will try to write a more detailed description of it by this weekend. I'll then gladly accept help to figure out the details and write the implementation.

Anyway, glad to learn this trait-handlers approach does not sound too silly to you. :smile:

My final goal would be to unify as much as possible the client and server sides of the lib, as they can be structurally very similar, and allow an easier integration of alternative protocols, without need to make a PR to my lib, but rather by making wayland-scanner easy to integrate in a build script, and making the generated code not need to introspect the lib internals.

**Comment by Timidger** [comment]
Sounds good. Though it's too bad `wayland-server` isn't usable yet, it does make feel better knowing that I wasn't crazy and I couldn't actually bind the protocol I wanted. I'll keep an eye on this project in the coming weeks.

**Comment by vberger** [comment]
Here is a first draft of my thoughts: https://gist.github.com/vberger/f4c6975c384ae5368283da897197453b

@Timidger, could you give me your feedback on it?

**Comment by Timidger** [comment]
I looked over, and the design feels much cleaner, though obviously several things have to be clearly defined. I'm especially interested to see what extra abstractions will be added onto the server side, since that's the part of the library that's not ready for prime time. Overall it seems like this is a general enough approach to work on both server and client.

Could you describe `EventLoopHandler` a little better and how it fits into `EventQueue` and `EventQueueHandler`? From what I understand, first you register a handler struct on `EventQueueHandler` w/ `register_handle`, and then you use that index it gives back in `EventLoopHandler`'s `assign` method to bind that to a proxy object representing one of the objects, eg `WlPointer`? So will the `Proxy` trait be exactly as it is now, since I didn't see it mentioned anywhere else in the document, and the primary way you bind it to a specific instance of a wayland object is to give it this proxy object to the concrete instance?

I tried it out by rewriting some current code I have that matches on the pointer entering a screen into your theoretical design. Tell me if this is what you had in mind and if I'm on the right track for where you want to go with this.

``` rust
/// Autogenerated from the protocol
trait WlPointerInterface {
    fn Enter(&mut self, queue: &mut EventQueueHandle, interface_name: &mut WlInterfaceName,
            serial: u32, surface: WlSurface, surface_x: i32, surface_y: i32);
    /* Other events defined here */
}

struct PointHandle {
    // Will this struct still exist, or is it now just the WlPointerInterface trait?
    // If so, where will `set_cursor` be, since it's not an event?
    pointer: WlPointer,
    // The surface we want to set the pointer to when we enter a window
    cursor_surface: WlSurface
}

impl WlPointerInterface for PointHanndle {
    fn Enter(&mut self, queue: &mut EventQueueHandle, interface_name: &mut InterfaceName,
             serial: u32, surface: WlSurface, surface_x: i32, surface_y: i32) {
        // This is where the pointer would live, right?
        // The one we bound below in event_loop.assign()?
        let pointer = queue.state().get_pointer();
        pointer.set_cursor(0, Some(&self.cursor_surface), 0, 0);
    }
    /* Other event methods implemented here */
}

wayland_env!(WaylandEnv,
            compositor: WlCompositor,
            shell: WlShell,
            shm: WlShm,
            seat: WlSeat
);


fn main() {
    let compositor = env.compositor.as_ref().map(|o| &o.0).unwrap();
    let seat = env.seat.as_ref().map(|o| &o.0).unwrap();
    let pointer = seat.get_pointer();
    let cursor_surface = compositor.create_surface();
    /* Put in code here to write stuff to the surface */
    /* The surface won't actually be bound to the pointer until the event is triggered */
    let point_handle = PointHandle {
        cursor_surface: cursor_surface
    };
    /* assuming I get the EventQueueHandle from some compositor instance */
    let mut event_queue = compositor.get_event_queue();
    /* Is this how I get the event_loop? Where else does it come from? */
    let mut event_loop = compositor.get_event_loop();
    let index = event_queue.register_handle(point_handle);
    event_loop.assign(index, &pointer);
    loop {
        event_queue.dispatch();
    }
}
```

**Comment by vberger** [comment]
Hmm, not exactly. What you represented as `iterface_name` was instead a placeholder for the name of the interface. The first half of your code would rather look like:

```rust
/// Autogenerated from the protocol
trait WlPointerHandler {
    fn Enter(&mut self, queue: &mut EventQueueHandle, pointer: &WlPointer,
            serial: u32, surface: &WlSurface, surface_x: i32, surface_y: i32);
    /* Other events defined here */
}

struct PointHandle {
    // The surface we want to set the pointer to when we enter a window
    cursor_surface: WlSurface
}

impl WlPointerHandler for PointHanndle {
    fn Enter(&mut self, queue: &mut EventQueueHandle, pointer: &WlPointer,
             serial: u32, surface: WlSurface, surface_x: i32, surface_y: i32) {
        pointer.set_cursor(0, Some(&self.cursor_surface), 0, 0);
    }
    /* Other event methods implemented here */
}
```

The idea is that all wayland object `wl_foo` will have two things generated: a struct `WlFoo` used to call its requests, and a trait WlFooHandler to handle its event (and symmetrically inverted for the server-side).

Regarding `wayland_env!` macro and the code you wrote in main... The `EventLoops` are directly created from the `WlDisplay` object (the `WlCompositor` protocol object is very different from the "wayland compositor server", actually). And for the rest, I cannot tell you a lot a priori except that it'll likely change a lot.

If I wrote `EventLoopHandler` somewhere, it's a typo, I meant `EventQueueHandler`. The general setup of a client application would be something like this (names are not final, and likely to change).

```rust
/*
 * First, declaration of all handler structs and implement of their traits.
 * For simple applications, a single struct will likely be required and will implement
 * several traits.
 */

fn main() {
    // Creating a connexion creates a default event queue as well, and the wl_display
    // object is associated with it, and cannot change of event queue.
    let (mut display, mut default_event_queue) = wayland::client::get_display();
    // It is possible to create other event queues via the display
    // but simple programs will likely not need it
    let _other_event_queue = display.create_event_queue();

    // Now, we can create handlers objects and register them to the event_queue
    // Initial protocol setup, and global objects instantiation will take place in the
    // handler callbacks.
    // Maybe the crate can provide an already-implemented handler struct for
    // this general case, and would replace the wayland_env macro.
    let handler = MyHandler::new();

    // A little shorthand
    let mut evq = default_event_queue;

    // Then, just run the event loop
    loop {
        // fetch events from the socket
        evq.fetch();
        // dispatch to the callbacks
        evq.dispatch();
        // Now, at this point, maybe we have other sources of events ?
        if let Some(something_to_do) = query_external_state() {
            // we can fetch an handle to the internal state
            // (which is the self in the callbacks)
            let mut state_guard = evq.state();
            // We fetch the first state, it is necessary to explicitly specify its
            // state, and the lib will panic if we try to fetch an incorrect type
            let mut state : &mut MyHandler = state_guard.get(0);
            do_something_with(state, something_to_do);
        }
    }
}
```

Is it more clear?

**Comment by Timidger** [comment]
Ah, ok that's much clearer, thank you. I really like this design now that I have a handle on it, it feels much more natural to Rust, especially given the difficult requirements with communicating with Wayland.

Do you have a rough time frame for all of this? I assume the shared common client/server part will be developed first so that both sides can be worked on in parallel. Since this is a fairly important project for my WM, I would be more than happy to offer any assistance needed especially on the server side of things.

**Comment by vberger** [comment]
Time frame, I can't really say, I expect to see unexpected difficulties to appear, as some parts of the design are still quite foggy.

I'll try to advance as much as possible this week though. I'll probably start working up in a new branch, from scratch. It'll be cleaner than to try transforming master.

**Comment by vberger** [comment]
Okay, I've started the [handlers branch](https://github.com/vberger/wayland-client-rs/tree/handlers), to start from it.

**Comment by vberger** [comment]
Well, I've hit a wall.

My design though was that each wayland interface define its `Handler` trait, and then everything is centralised into a general `Handler<T>` trait, via automatic impls generated by the scanner like

```rust
impl<T> Handler<WlSurface> for T where T: wl_surface::Handler { ... }
```

Hoping downscteam crates would then easily use the scanner to implement their own protocol files.

However, it appears that this is forbidden by coherence rules, specifically I'm having a problem very similar to https://github.com/rust-lang/rfcs/issues/1113.

So... I'll need to find an other approach, I guess, as this issue does not seem to be anywhere near being addressed in short term.

**Comment by vberger** [comment]
Okay, I side-stepped the issue in 184aaf052f73151db2047128ebe5d73741d872ee, but it forces one more step to the user. Now, they need to implement the handler traits _and_ declare them using the `declare_handler!` macro.

This is not ideal, but it'll do for now.

**Comment by Timidger** [comment]
Hm, a slight annoyance but probably fine for now. Good to hear work is underway on this, perhaps you should post about the issue on that RFC page to try and bring more light to this problem.

**Comment by vberger** [comment]
I have a basic client which just lists global objects, see https://github.com/vberger/wayland-client-rs/blob/handlers/wayland-client/examples/simple_client.rs

What do you think of how it looks, @Timidger ?

**Comment by Timidger** [comment]
Without digging into the internals, looks much easier to use so far. Shame about the `declare_handler!` boiler plate, but it's a relatively small blemish, the api design seems much nicer. I'm hoping it works out just as well on the server side.

**Comment by vberger** [comment]
Just noting here an important design question: what to do if an handler panics during a callback?

We have no way to report failure to the wayland lib, and we cannot let the unwinding propagate to C code... so... just abort ?

**Comment by Timidger** [comment]
Yeah unfortunately that might be the only answer here. You'd wanna specify you shouldn't panic when in a callback in the docs somewhere, because otherwise it might be confusing when suddenly your code aborts and you can't find where.

**Comment by vberger** [comment]
Maybe It'd help if we could still print the stacktrace (like a regular panic) up to the `catch_panic!`, to help debug, and then abort.

I'll look into that.

**Comment by vberger** [comment]
Regarding the server side, I'm going to mirror as much as possible the design of the client side, except I'll leave aside the "multiple event-loop" part aside for now.

I'm not entirely sure how they are supposed to be used (partly due to no documentation on the C API about them), but I think they are only relevant for wayland compositors listening on more than one socket for clients. Which is definitely not a basic use-case.

I'll also need to understand how signal/listeners work exactly, as they have no client-side equivalent either, and see how I can integrate them in the API as well.

Are you by chance familiar with these things @Timidger ? I could use some insight.

**Comment by Timidger** [comment]
Unfortunately no sorry, I didn't get a chance to look into signals / listeners, since we are going with a different system to handle that in our compositor (using dbus ipc)

**Comment by vberger** [comment]
I have enough basic work in place now, I've backed up the old implementation in the `v0.6.x` branch, and the new implementation is now `master`.

I'll update the README and the docs to make sure noone gets lost, and then do some cleanup on the issues to track the progress and the stuff to do.

**Comment by YaLTeR** [comment]
Sorry for resurrecting this thread, but what happened to this initiative? Trying out `wayland-client` and `wayland-protocols`, it seems to suffer from the exact problems outlined in the issue: the user needs to provide `Send + 'static` callbacks which litter the code with `Arc<Mutex<_>>` even for simple single-threaded applications. Additionally, handling events by matching on an `enum` instead of implementing traits with corresponding methods feels odd.

**Comment by vberger** [comment]
The lib has gone through several design iterations since this discussion occurred, and I had time to reevaluate the trade-offs while using these libs in sctk, winit and smithay.

First of all, the `Send + 'static` callbacks can be avoided with the [`implement_nonsend`](https://docs.rs/wayland-client/0.21.10/wayland_client/struct.NewProxy.html#method.implement_nonsend) methods. `'static` is still required though, reducing `Arc<Mutex<_>>` to `Rc<RefCell<_>>`. Note that you can also use the [user data mechanism](https://docs.rs/wayland-client/0.21.10/wayland_client/struct.Proxy.html#method.user_data) which allows you to attach some data to an object, depending on your needs.

Matching on an enum makes possible to implement an object using a closure, which is a huge ergonomic implement in many cases where the implementation is very small. On the other hand, it always remain possible to using a small match to dispatch the events to different methods of an object captured by the closure. Additionally, the previous handler-trait-based design required a lot of macro boilerplate from the users to work correctly with coherence rules.

In the end, it appeared to me that letting wayland-client's user deal with the `Arc<Mutex<_>>` actually was less boilerplate for them to handle than the huge machinery that was previously in place to try and hide them.

**Comment by vberger** [comment]
Now, I am still open to serious redesign of the API (there is a reason why these libs are not 1.0 yet), and if you have some concrete idea on how it could be improved, please by all means open an issue to discuss it!

You can have some background on my previous iterations of the API in these blog posts:

- https://levans.fr/wayland_rust_v3.html
- https://smithay.github.io/wayland-rs-v-0-20.html
- https://smithay.github.io/wayland-rs-v-0-21.html
