### ISSUE TITLE
Creating a cursor surface

### ISSUE THREAD

**Issue by chrisduerr** [vberger/wayland-client-rs#85]
So since by default Wayland doesn't show any cursor I wanted to make that work for my app.

I was looking at https://docs.rs/wayland-client/0.7.6/wayland_client/protocol/wl_pointer/struct.WlPointer.html#method.set_cursor and apparently that just registers a surface as a cursor. I'm assuming that I can now render my cursor using a normal WlShmPool.

However `set_cursor` requires not only a WlSurface (which shouldn't be a problem), but also a WlPointer. This WlPointer doesn't seem to get exported to wayland_env and the only way I can find how to acquire such a WlPointer object would be using an event handler like `wl_pointer::Handler::enter`.

I now want to know if I really need to register an event handler for the mouse to enter the window to pass that to my set_cursor method for registering a surface which will then draw my cursor.
This seems a little odd to me so I just wanted to know if there is any other way of doing this.

**Comment by vberger** [comment]
Hmm, by default the cursor should be drawn by the compositor using its theme...

Anyway, yes, first of all, you need to get a pointer from [`WlSeat::get_pointer()`](https://docs.rs/wayland-client/0.7.7/wayland_client/protocol/wl_seat/struct.WlSeat.html#method.get_pointer)

Once you have this pointer, you can register an handler to it. You then need to call `WlPointer::set_cursor()` with your cursor surface every time the pointer enters a surface you own, so the `wl_pointer::Handler::enter` event is indeed a good place to do that. You don't need to create a new cursor surface every time, you can re-use the same every time.

You can then draw on this surface like any other surface, by assigning a buffer to it.

Also, note that if you want your cursors to match the system's theme, you can use [the `cursor` feature of wayland-client](https://docs.rs/wayland-client/0.7.7/wayland_client/cursor/index.html).

Did I answer your question?

**Comment by chrisduerr** [comment]
Yeah you did. My main question was if I really need to register an event for getting the WlPointer object. And even tho it's kinda weird I guess I can make it work.

And the cursor is not drawn by default in Sway. I even asked in the irc and you need to create a surface and then draw the cursor yourself for it to work.

**Comment by vberger** [comment]
You don't need to register an event for getting the `WlPointer`, you get it through `WlSeat::get_pointer()`.

However, you need to register an handler to know when then pointer enters your surface, in order to call `set_cursor()` in response.

**Comment by vberger** [comment]
But you need to register an handler to `WlSeat` to make sure it has the pointer capability, though.

**Comment by chrisduerr** [comment]
Is it not possible to get the `WlPointer` from the `enter` event?
I've tried to make this work like this:
https://gist.github.com/chrisduerr/d54e71ba3a33a0d2a9b19a4d2b8c6b54

The issue seems to be that the surface doesn't survive? It shouldn't matter if I check for pointer capability if that capability exists, right?

If I render the cursor buffer to the window itself it seems to work just fine. However if I take the buffer and attach it to the cursor_surface it doesn't work.

**Comment by vberger** [comment]
There are two things missing with your code:

- first of all, you need to keep the `CursorTheme` alive, as it maintains the memory map containing the theme data
- secondly, you need to attach the buffer & commit the surface every time you call `set_cursor`.

Here's an example of your code with these modifications (I only tested it on weston though): https://gist.github.com/vberger/4f1ea21fb7fc712642343f71f46519ee

**Comment by vberger** [comment]
Also, if you don't want to handle all this by hand, you can give a look at [`wayland_window`](https://docs.rs/wayland-window/). Even if you set `window.set_decorate(false)`, it should still handle pointer updating.

**Comment by chrisduerr** [comment]
I'm not sure if using `wayland_window` would be viable for me since I'm creating a bar which has to use the `set_panel` call. So no decorations or stuff like that going on.

If it's still usable for that purpose and good practice to rely on that stuff I'd love to check it out tho. For now I think I should be able to make this work.

**Comment by vberger** [comment]
Oh, ok, if your use-case is specific that wayland_window will not be appropriate, it's specifically targeted at the "give me a window with basic decorations" use-case (like the winit backend for example).

Also... what is this `set_panel` call? A custom protocol for sway?

**Comment by chrisduerr** [comment]
`set_panel` is part of the `desktop-shell.xml` protocol and should be implemented by most WMs from what I can tell. 
(https://github.com/SirCmpwn/sway/blob/5778c59a2f302071fd781683db57a97b51396c87/protocols/desktop-shell.xml#L15)

**Comment by vberger** [comment]
Oh right, not yet in https://cgit.freedesktop.org/wayland/wayland-protocols/ though

**Comment by chrisduerr** [comment]
So I just tested it and I was able to make it work with sway. Thanks for the help!
